identify_key_aspects_prompt = """
You are an expert qualitative researcher skilled at deconstructing complex theoretical concepts (code) into their core components for analysis.

Your task is to analyze the provided qualitative code, which might consists of a name and a definition used in research. Break down this code into its distinct key aspects or sub-components. These aspects should represent the fundamental activities, considerations, or dimensions embedded within the code's definition.

<code to deconstruct into core components>
Calibrating the approach: Changing the charity’s intervention depending
on the specifics of the location.
</code to deconstruct into core components>

**Instructions:**
1.  **Analyze:** Carefully read the code name and definition. Understand the core process or concept it represents in the context of charity operations.
2.  **Deconstruct:** Identify the distinct, fundamental parts that make up this concept. Think about:
    * What specific actions or stages are involved in this process?
    * What key factors or elements are being considered or managed?
    * What are the essential dimensions or facets of this code?
3.  **Formulate Aspects:** Express each distinct part as a concise key aspect (a short phrase or descriptive statement). Aim for a level of granularity that is useful for detailed analysis (typically 3-6 aspects, but adjust based on code complexity).
4.  **Ensure Distinction:** Each aspect should capture a unique facet of the code, avoiding significant overlap.
5.  **Format Output:** Present the results **strictly** as a JSON object. This object must contain a single key named `key_aspects`. The value for this key must be a list of strings, where each string is one identified key aspect.

**Example Input:**

* **Name:** `Pre-intervention data collection`
* **Definition:** `Collecting information about the charitable cause before implementing the charity’s intervention.`

**Example Output Format:**

```json
{
  "key_aspects": [
    "Identifying information needs relevant to the cause",
    "Choosing data collection methods/sources",
    "Executing data gathering activities",
    "Timing data collection before intervention starts",
    "Analyzing/using collected data to inform intervention"
  ]
}
(Note: The actual aspects generated by the AI for the example might differ slightly, this is illustrative)

Constraint Checklist:
Output MUST be valid JSON.
JSON object MUST have only one key: key_aspects.
The value of key_aspects MUST be a list of strings.
Each string in the list MUST be a concise key aspect.
Do NOT include explanations or text outside the JSON object.
Now, analyze the provided Input Code and generate the JSON output containing the key aspects.
"""


# Export the variables
__all__ = [
    'identify_key_aspects_prompt'
]
