identify_key_aspects_prompt = """
You are an expert qualitative researcher skilled at deconstructing complex theoretical concepts (code) into their core components for analysis.

Your task is to analyze the provided qualitative code, which might consists of a name and a definition used in research. Break down this code into its distinct key aspects or sub-components. These aspects should represent the fundamental activities, considerations, or dimensions embedded within the code's definition.

<code to deconstruct into core components>
Calibrating the approach: Changing the charity’s intervention depending
on the specifics of the location.
</code to deconstruct into core components>

**Instructions:**
1.  **Analyze:** Carefully read the code name and definition. Understand the core process or concept it represents in the context of charity operations.
2.  **Deconstruct:** Identify the distinct, fundamental parts that make up this concept. Think about:
    * What specific actions or stages are involved in this process?
    * What key factors or elements are being considered or managed?
    * What are the essential dimensions or facets of this code?
3.  **Formulate Aspects:** Express each distinct part as a concise key aspect (a short phrase or descriptive statement). Aim for a level of granularity that is useful for detailed analysis (typically 3-6 aspects, but adjust based on code complexity).
4.  **Ensure Distinction:** Each aspect should capture a unique facet of the code, avoiding significant overlap.
5.  **Format Output:** Present the results **strictly** as a JSON object. This object must contain a single key named `key_aspects`. The value for this key must be a list of strings, where each string is one identified key aspect.

**Example Input:**

* **Name:** `Pre-intervention data collection`
* **Definition:** `Collecting information about the charitable cause before implementing the charity’s intervention.`

**Example Output Format:**

```json
{
  "key_aspects": [
    "Identifying information needs relevant to the cause",
    "Choosing data collection methods/sources",
    "Executing data gathering activities",
    "Timing data collection before intervention starts",
    "Analyzing/using collected data to inform intervention"
  ]
}
(Note: The actual aspects generated by the AI for the example might differ slightly, this is illustrative)

Constraint Checklist:
Output MUST be valid JSON.
JSON object MUST have only one key: key_aspects.
The value of key_aspects MUST be a list of strings.
Each string in the list MUST be a concise key aspect.
Do NOT include explanations or text outside the JSON object.
Now, analyze the provided Input Code and generate the JSON output containing the key aspects.
"""

identify_intervention = """
You are a qualitative research analyst.

INPUTS  
• Research question: 
  <research_question>
  {research_question}  
  </research_question>
• Codes (for context only):
  <codes>
  {codes}  
  </codes>
• Case texts (markdown):  
  <texts>
  {texts}
  </texts>

TASK  
1. Read the case texts, ignoring markdown formatting.  
2. From all available details, pinpoint the **single intervention** (i.e. the main action, program, policy, or practice that is implemented in this case).

OUTPUT  
Write **one clear sentence (≤ 30 words)** that describes that intervention.  
- Start with an action verb.  
- Make the sentence self-contained; include enough context so it can stand alone.  
- Return *only* that sentence—no labels, headings, or extra text.
"""

identify_evidence_prompt = """
You are a meticulous qualitative-methods researcher (Ph.D. level). Your task is to analyze the provided text based on the defined research focus and extract relevant evidence using a specific tool.

# 1. Research Focus
This research investigates:
<code>
{code}
</code>

Key aspects being examined:
<aspects>
{aspects}
</aspects>

Central Research Question:
<research_question>
{research_question}
</research_question>

The Intervention Studied:
<intervention>
{intervention}
</intervention>

Note: The research_question and other Research Focus details are included intentionally. Use this context to accurately interpret the purpose, significance, and chronology of the evidence you identify in the text.

# 2. Your Task
Read the provided text carefully. Identify and extract all passages (evidence) that are **relevant to the research `<code>` and relate to at least one defined `aspect`**.

For **each piece of evidence** you identify, you **must** log it using the `log_quote_reasoning` tool.

# 3. Chronological Awareness
The intervention serves as a key temporal marker. For every piece of evidence extracted, determine its timing relative to the intervention **based on the context of the full text**:

* `before`: The event/statement clearly precedes the intervention period.
* `during`: The event/statement occurs while the intervention is actively running.
* `after`: The event/statement occurs after the intervention period has concluded.
* `unclear`: The timing relative to the intervention cannot be reliably determined from the text.

Consider if the `<code>` definition or a specific `aspect` implies a relevant timeframe. If timing is significant for understanding the evidence's link to the code/aspect, mention this in your reasoning.

# 4. Definition of Evidence
Evidence can include:
1. Direct statements: Explicit passages discussing the code or an aspect.
2. Descriptive narratives: Stories or examples illustrating the code or an aspect in action.
3. Contextual explanations: Background information that clarifies *how or why* something related to the code/aspect occurred.
4. Recurring themes/patterns: Repeated language or ideas indicating the presence or nature of the code/aspect.
5. Contradictions / Ambiguities / Multiple Meanings: Passages presenting conflicting views, uncertainty, or statements potentially open to multiple plausible interpretations (e.g., literal meaning vs. strategic intent like a publicity stunt) related to the code/aspect.
6. Explicit statements of absence: Text specifically stating that certain data, actions, or phenomena related to the code/aspect are missing or did not occur.
7. Exception-to-rule statements: Passages noting that a usual **practice or aspect was skipped, modified, or done differently** (e.g., “We did not collect baseline data this time due to time pressure”). Such exceptions imply the rule’s normal existence and therefore constitute evidence about standard practice.

# 5. Tool Usage: Logging Evidence (`log_quote_reasoning`)
You **must** call the `log_quote_reasoning` tool for **every** piece of evidence you extract.

## Tool Schema: log_quote_reasoning
```json
{
  "quote":       "<string>",            
  "reasoning":   "<string>",            
  "aspect":      ["<aspect>", …],  
  "chronology":  "before" | "during" | "after" | "unclear"  
}
```
Tool Input Field Descriptions:
- quote: The full, unaltered text passage extracted as evidence. Do not truncate or paraphrase.
- reasoning: Your explanation for logging this quote. Address the following points clearly:
1. Relevance: Explain *precisely* why this quote serves as evidence for the research `<code>` and how it relates to the specified `aspect`(s).
2. Timing Context: Briefly note significant timing details relative to the intervention (as defined by `chronology`), if applicable and insightful for understanding the evidence.
3. Motivation/Cause Analysis (If Text Allows): Analyze and explain the apparent *reason or motivation* behind the action or statement described in the quote, based *only* on information present in the text.
4. Handling Multiple Interpretations (If Applicable): Explicitly identify if the quote (especially a statement) could support multiple plausible interpretations (e.g., literal vs. strategic/performative). State that acknowledging this complexity is part of the analysis and does not automatically weaken the quote's value as evidence.
5. Exception Analysis (If Applicable): If the quote describes an exception to a norm, explain how it implicitly clarifies or confirms the standard practice.
- aspect: A list containing the id(s) of all the specific aspects from the <aspects> list that the quote is relevant to. If the quote is relevant to the overall research <code> or intervention but doesn't fit a specific aspect, use ["general"].
- chronology: The timing of the evidence relative to the intervention, chosen from the four defined categories (before, during, after, unclear), based on full text context.


# 6. Instructions
Understand: Thoroughly read and internalize the research <code>, <aspects>, <research_question>, and <intervention> details.
Scan & Identify: Read the provided text, actively looking for passages that constitute evidence (as defined in #4) related to the <code> and any of the aspects.
Extract: Carefully copy the full, exact quote for each piece of evidence.
Analyze & Reason: For each quote, determine why it's relevant evidence, which aspect(s) it pertains to, and its chronology relative to the intervention (using context). Formulate your reasoning.
Log: Call the log_quote_reasoning tool with the quote, reasoning, list of aspects, and chronology for each piece of evidence found. Continue this process until the entire text has been analyzed.

# 7. Required Output
Your response should consist only of calls to the log_quote_reasoning tool. Do not provide any introductory text, concluding summary, or any other output besides the tool calls.

# 8. Prohibited Actions
Do not paraphrase or alter quotes. Extract them verbatim.
Do not infer evidence from the absence of mention unless the text explicitly states something is missing (see Evidence type #6).
Do not provide any output other than calls to the log_quote_reasoning tool.
"""

synthesize_evidence = """
You are a meticulous qualitative-methods researcher (Ph.D. level) performing thematic analysis and critical assessment of evidence. Your task is to analyze the provided set of extracted evidence records related to a specific research code within a case study. Your goal is to identify dominant content themes, note relevant dimensional characteristics, flag any direct contradictions or strong singular claims present in the data, and select representative quotes. Your analysis must be systematic and grounded solely in the provided data records.

# Context
Use the context (Research Question, Research Code, and Intervention) to understand the significance of the themes and findings you identify within the provided records as they relate to the specific Research Code.
## Case Name: 
{case_name}
## Research Code (name and description): 
{code}
## Research Question (Optional Context): 
{research_question}
## Intervention: 
{intervention}

# Input Data Format
You will be provided with a batch of evidence records below under "data to analyze". Each record contains fields like `record_id`, `quote`, `reasoning`, `aspect` (list), `chronology`, and `doc_name`.

# Task Overview
Analyze the provided batch data to:
1.  Identify the most prominent **Content Themes**.
2.  Identify any prominent **Dimensional Themes**.
3.  Identify any **Direct Contradictions** within this batch.
4.  Identify any **Strong Singular Claims** within this batch.
5.  Select **Exemplar Quotes** representing the core content themes.

# Detailed Instructions

## General Guidance: Prioritize Direct Evidence (Quotes)
**Core Principle:** Your analysis MUST be primarily based on the `quote` field for each record. The `quote` contains direct evidence extracted from the source text and is the most reliable data point.
**Using Reasoning:** Treat the associated `reasoning` field as a potentially helpful *initial interpretation* generated previously by an LLM. It can guide your understanding or suggest potential themes, but **you must critically evaluate it and always verify any insights derived from the `reasoning` against the actual `quote` content.**
**Hierarchy:** If the `reasoning` seems inconsistent with, misinterprets, or contradicts the `quote`, **the information directly present in the `quote` takes precedence.** The quote is the ground truth for your analysis in this phase.

## 1. Identifying Content Themes (Focus: What is being discussed?)
- 1.1 Analyze: Primarily analyze the `quote` content across all records to identify themes. Refer to the `reasoning` and `aspect` fields as supplementary guides or initial hypotheses about the quote's relevance/meaning, **always validating against the `quote` itself.
- 1.2 Identify Concepts: Look for recurring concepts, activities, beliefs, etc., related to Research Code.
- 1.3 Group & Synthesize: Group records discussing similar concepts. For each group representing a distinct and significant theme within the dataset, synthesize and articulate its **core concept or central idea**. Focus on themes that meaningfully recur or capture important facets of the code as represented in the data.
- 1.4 Create a word label for each theme.

## 2. Identifying Dimensional Themes (Focus: How is it being discussed?)
- 2.1 Analyze: Look for recurring characteristics in *how* the evidence related to the research code is presented across the records.
- 2.2 Identify dimensional characteristics **if** they are notably prominent or recurring across a significant portion of the provided records.
- 2.3 Create a label for each.

## 3. Identifying Direct Contradictions (Focus: Conflicting Statements within this Batch)
- 3.1 Scan Critically:** Specifically search the records for instances where the `quote` content presents directly opposing information, claims, or perspectives regarding the research code '{code}'. Use the `reasoning` field *only cautiously* as a potential pointer to conflicts, but **base the identification of a contradiction primarily on conflicting `quote` texts.
- 3.2 Report Findings: If contradictions are found, list each instance clearly. Note the `record_id`s involved and briefly describe the nature of the contradiction. If none are found in this batch, state that explicitly.
- 3.3 Example: "Contradiction found regarding standard practice for pre-intervention data collection: some evidence states it is always done, while other evidence suggests it is often skipped or done hastily."

## 4. Identifying Strong Singular Claims (Focus: Definitive Statements)
- 4.1 Scan Critically: Look for individual records where the `quote` contains a particularly strong, definitive, absolute, or impactful statement [...]. **Focus solely on the quote text** for identifying these claims.
- 4.2 Report Findings:** If such claims are found, list the `record_id` and the full `quote`. Limit this to 1-3 truly notable examples per batch, if found. If none are found, state that explicitly.
* **Example:** "Strong Claim Identified: Standard practice requires baseline surveys always be completed before fund disbursement." OR "Strong Claim Identified: 'It is impossible to measure impact without baseline data.'"

## 5. Selecting Exemplar Quotes (Focus: Representing Dominant Themes)
- 5.1 Review Content Themes:** Refer back to the primary Content Themes identified in step 1.
- 5.2 Select Quotes:** From the *entire batch*, select 2-3 quotes based on these criteria:
    * **Representativeness:** Clearly illustrates one or more *most central/frequent* Content Themes.
    * **Conciseness & Clarity:** Prefer shorter, clearer quotes.
- 5.3 Extract Details:** Provide the original `record_id` and the full `quote` text for each.

# Data to analyze
<data to analyze>
{data}
</data to analyze>

# Output Format
Provide your complete output as a clearly structured text report using Markdown headings. Do not include any introductory or concluding explanatory text outside the specified structure. Ensure the output is self-contained and does not reference specific record IDs.

# Example Output Structure:
## Content Themes
* Concise Label 1
* Concise Label 2
* Concise Label 3

## Dimensional Themes
* Concise Label A

## Direct Contradictions
* [Description of contradiction 1, summarizing the conflicting points]
* [Description of contradiction 2, summarizing the conflicting points]

## Strong Singular Claims
* [Claim 1, e.g., "Standard practice requires baseline surveys always be completed..."]
* [Claim 2, e.g., "'It is impossible to measure impact without baseline data.'"]

## Exemplar Quotes (Representing Content Themes)
* [Full text of quote 1...]
* [Full text of quote 2...]
* [Full text of quote 3...]
"""


# Export the variables
__all__ = [
    'identify_key_aspects_prompt', 
    'identify_intervention', 
    'identify_evidence_prompt',
    'synthesize_evidence'
]
